# Configuration for Rasa NLU.
language: en
pipeline:
- name: SpacyNLP
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: SklearnIntentClassifier

# Configuration for Rasa Core.
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
